import Head from 'next/head'
import { MongoClient, ServerApiVersion } from 'mongodb'
import ProjectsData from '@/components/ProjectsData';

export default function Home(props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ProjectsData projectsData={props.projectsData} />
      </main>
    </>
  )
}

export async function getServerSideProps(context) {
  // console.log('mongoURL:: ', process.env.MONGO_URL);
  const url = process.env.MONGO_URL;
  const client = new MongoClient(url, {
    serverApi: {
      version: ServerApiVersion.v1,
      strict: true,
      deprecationErrors: true,
    }
  });
  
  await client.connect();
  await client.db(process.env.ADMINDB).command({ ping: 1 });

  const db = client.db(process.env.DATABASE);
  const projectsDataCollection = db.collection(process.env.COLLECTION);

  const projectsData = await projectsDataCollection.find({}).toArray();


  client.close();

  return {
    props: {
      projectsData: projectsData.map((projectData) => {
        return ({
          project: projectData.Project,
          technicalSkillSet: projectData.Technical_Skillset,
          id: projectData._id.toString(),
        })
      }),
    }
  };
}
